# Generated by Django 4.2.6 on 2024-01-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docfile", models.FileField(upload_to="documents/%Y/%m/%d")),
            ],
        ),
    ]
